"""  
Tool: generate_excel_from_testcases  
------------------------------------  
Converts a JSON object containing test cases (as generated by your LLM agent)  
into a formatted .xlsx file.  
   
Install dependencies:  
    pip install pandas openpyxl  
   
Expected input JSON shape:  
{  
  "test_cases": [  
    {  
      "id": "TC001",  
      "title": "Verify login with valid credentials",  
      "preconditions": "User is registered",  
      "steps": ["Open login page", "Enter valid username/password", "Click login"],  
      "expected_result": "User is redirected to dashboard",  
      "priority": "High"  
    },  
    ...  
  ]  
}  
   
Extra/missing fields are handled gracefully — any keys present across the  
test cases become columns automatically.  
"""  
   
import json  
import os  
import re
from datetime import datetime  
   
import pandas as pd  
from openpyxl import load_workbook  
from openpyxl.styles import Alignment, Font, PatternFill  
from openpyxl.utils import get_column_letter  
   
   
def generate_excel_from_testcases(  
    json_data,  
    output_path: str = None,  
    sheet_name: str = "Test Cases",  
    steps_as_single_cell: bool = True,  
):  
    """  
    Convert test case JSON into an Excel file.  
   
    Args:  
        json_data: dict OR JSON string. Must contain a "test_cases" key  
                    whose value is a list of dicts.  
        output_path: optional path/filename for the output .xlsx file.  
                      Defaults to 'test_cases_<timestamp>.xlsx' in the  
                      current directory.  
        sheet_name: name of the worksheet tab.  
        steps_as_single_cell: if True, list-type "steps" fields are joined  
                      into one cell like "1. Open page\\n2. Enter creds...".  
                      If False, steps are expanded into Step 1, Step 2, ...  
                      separate columns.  
   
    Returns:  
        str: absolute path to the generated .xlsx file.  
   
    Raises:  
        ValueError: if json_data is invalid or has no test cases.  
    """  
   
    # --- 1. Parse input ---------------------------------------------------  
    if isinstance(json_data, str):  
        try:  
            json_data = json.loads(json_data)  
        except json.JSONDecodeError as e:  
            raise ValueError(f"Invalid JSON string passed to tool: {e}")  
   
    if not isinstance(json_data, dict) or "test_cases" not in json_data:  
        raise ValueError('JSON must be an object containing a "test_cases" list.')  
   
    test_cases = json_data["test_cases"]  
    if not isinstance(test_cases, list) or len(test_cases) == 0:  
        raise ValueError('"test_cases" must be a non-empty list.')  
   
    # --- 2. Normalize rows ---------------------------------------------------  
    rows = []  
    max_steps = 0  
   
    for i, tc in enumerate(test_cases, start=1):  
        if not isinstance(tc, dict):  
            raise ValueError(f"test_cases[{i - 1}] is not a JSON object.")  
   
        row = dict(tc)  # shallow copy so we don't mutate original  
   
        steps = row.get("steps")  
        if isinstance(steps, list):  
            if steps_as_single_cell:  
                row["steps"] = "\n".join(f"{j}. {s}" for j, s in enumerate(steps, 1))  
            else:  
                max_steps = max(max_steps, len(steps))  
                for j, s in enumerate(steps, 1):  
                    row[f"Step {j}"] = s  
                del row["steps"]  
   
        # Ensure there's always an id, generate one if missing  
        row.setdefault("id", f"TC{i:03d}")  
   
        rows.append(row)  
   
    df = pd.DataFrame(rows)  
   
    # --- 3. Order columns sensibly -------------------------------------------  
    preferred_order = ["id", "title", "preconditions"]  
    if steps_as_single_cell:  
        preferred_order.append("steps")  
    else:  
        preferred_order += [f"Step {j}" for j in range(1, max_steps + 1)]  
    preferred_order += ["expected_result", "priority"]  
   
    ordered_cols = [c for c in preferred_order if c in df.columns]  
    remaining_cols = [c for c in df.columns if c not in ordered_cols]  
    df = df[ordered_cols + remaining_cols]  
   
    # Nicely capitalize headers, e.g. "expected_result" -> "Expected Result"  
    df.columns = [  
        c if c.startswith("Step ") else c.replace("_", " ").title() for c in df.columns  
    ]  
   
    # --- 4. Write to Excel ----------------------------------------------------  
    if output_path is None:  
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")  
        output_path = f"test_cases_{timestamp}.xlsx"  
   
    df.to_excel(output_path, index=False, sheet_name=sheet_name)  
   
    # --- 5. Formatting pass (header styling, column widths, wrap text) -------  
    wb = load_workbook(output_path)  
    ws = wb[sheet_name]  
   
    header_fill = PatternFill(start_color="305496", end_color="305496", fill_type="solid")  
    header_font = Font(color="FFFFFF", bold=True)  
    wrap_alignment = Alignment(wrap_text=True, vertical="top")  
   
    for col_idx, col_name in enumerate(df.columns, start=1):  
        cell = ws.cell(row=1, column=col_idx)  
        cell.fill = header_fill  
        cell.font = header_font  
        cell.alignment = Alignment(horizontal="center", vertical="center")  
   
        # Auto width based on content, capped so long text wraps instead  
        max_len = max(  
            [len(str(col_name))]  
            + [len(str(v)) for v in df[col_name].astype(str).tolist()]  
        )  
        col_letter = get_column_letter(col_idx)  
        ws.column_dimensions[col_letter].width = min(max(max_len + 2, 12), 50)  
   
        for row_idx in range(2, len(df) + 2):  
            ws.cell(row=row_idx, column=col_idx).alignment = wrap_alignment  
   
    ws.freeze_panes = "A2"  # keep header visible while scrolling  
    wb.save(output_path)  
   
    return os.path.abspath(output_path)


def _stringify_value(value, level: int = 0) -> str:
    """
    Recursively render a nested value (dict/list/scalar) as clean, indented,
    human-readable multi-line text - never raw Python/JSON syntax.

    Examples:
      {"System": "configured", "Service": "up"}
        -> "System: configured\nService: up"

      [{"Step": "Do X", "Expected Result": "Y happens"}, {...}]
        -> "1.\n  Step: Do X\n  Expected Result: Y happens\n2.\n  ..."
    """
    indent = "  " * level

    if value is None:
        return ""

    if isinstance(value, dict):
        lines = []
        for k, v in value.items():
            if isinstance(v, (dict, list)) and v:
                lines.append(f"{indent}{k}:")
                lines.append(_stringify_value(v, level + 1))
            else:
                lines.append(f"{indent}{k}: {_stringify_value(v, level)}")
        return "\n".join(lines)

    if isinstance(value, list):
        lines = []
        for i, item in enumerate(value, 1):
            if isinstance(item, (dict, list)) and item:
                lines.append(f"{indent}{i}.")
                lines.append(_stringify_value(item, level + 1))
            else:
                lines.append(f"{indent}{i}. {_stringify_value(item, level)}")
        return "\n".join(lines)

    return str(value)


def _flatten_row(row: dict) -> dict:
    """
    Make a dict Excel-friendly: any nested dict/list value (at any depth)
    becomes clean, readable multi-line text in that single cell.
    Scalar values are left untouched.
    """
    flattened = {}
    for key, value in row.items():
        if isinstance(value, (dict, list)):
            flattened[key] = _stringify_value(value)
        else:
            flattened[key] = value
    return flattened


def _to_records(json_data):
    """
    Normalize arbitrary JSON into a list of flat dict "records" (rows),
    where each top-level key of a record becomes an Excel column.

    Handles:
      - A bare list of records: [ {...}, {...} ]
      - A single-key wrapper around a list of records: {"test_cases": [ {...}, {...} ]}
      - A single-key wrapper around ONE record: {"Test Cases": {...}}
        (the case that was previously mis-rendered as one big text blob)
      - Columnar data: multiple keys, each an equal-length list of scalars:
        {"Name": ["A", "B"], "Age": [1, 2]}
      - A single flat/nested record with no wrapper: {...}
      - A bare scalar or list of scalars (wrapped into a "Value" column)
    """
    if isinstance(json_data, list):
        records = json_data if json_data else [{}]

    elif isinstance(json_data, dict):
        if len(json_data) == 1:
            only_value = next(iter(json_data.values()))
            if isinstance(only_value, list):
                # e.g. {"test_cases": [ {...}, {...} ]}
                records = only_value if only_value else [{}]
            elif isinstance(only_value, dict):
                # e.g. {"Test Cases": {...single record...}}
                records = [only_value]
            else:
                # e.g. {"Result": "some scalar"}
                records = [json_data]
        else:
            list_values = {k: v for k, v in json_data.items() if isinstance(v, list)}
            non_list_keys = [k for k, v in json_data.items() if not isinstance(v, list)]

            if (
                list_values
                and not non_list_keys
                and len({len(v) for v in list_values.values()}) == 1
            ):
                # Columnar orientation: every value is a list of the same length
                length = len(next(iter(list_values.values())))
                keys = list(json_data.keys())
                records = [{k: json_data[k][i] for k in keys} for i in range(length)]
            else:
                # A single record with multiple top-level fields (possibly nested)
                records = [json_data]
    else:
        # Bare scalar
        records = [{"Value": json_data}]

    # Ensure every record is a dict (wrap stray scalars/lists defensively)
    normalized = []
    for r in records:
        normalized.append(r if isinstance(r, dict) else {"Value": r})
    return normalized


def _prettify_header(col_name: str) -> str:
    """
    Convert a column name into a readable header.
    - "test_objective" -> "Test Objective"
    - "TestCaseID"      -> "Test Case ID" (splits CamelCase, keeps acronyms intact)
    - "Test Case ID"    -> left as-is (already contains spaces / is readable)
    """
    if not isinstance(col_name, str):
        return str(col_name)

    # Already has whitespace -> already human-readable, don't touch it.
    if " " in col_name.strip():
        return col_name

    if "_" in col_name:
        return col_name.replace("_", " ").title()

    # Split CamelCase / PascalCase into words, keeping consecutive capitals
    # (like "ID") together as one word.
    words = re.findall(r"[A-Z]+(?=[A-Z][a-z]|\b)|[A-Z]?[a-z]+|[A-Z]+|\d+", col_name)
    if len(words) > 1:
        return " ".join(words)
    return col_name


def generate_excel_from_json(
    json_data,
    output_dir: str = "downloads",
    sheet_name: str = "Data"
):
    """
    Generic Excel generator that can handle any JSON structure.
    If "test_cases" key exists, uses the specialized test case formatter.
    Otherwise, creates a generic Excel from the JSON data.
    
    Args:
        json_data: dict OR JSON string containing data to export
        output_dir: directory to save the file
        sheet_name: name of the worksheet tab
    
    Returns:
        dict with file_path and file_name
    """
    # Parse JSON if string
    if isinstance(json_data, str):
        try:
            json_data = json.loads(json_data)
        except json.JSONDecodeError as e:
            raise ValueError(f"Invalid JSON string: {e}")
    
    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)
    
    # Generate filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"export_{timestamp}.xlsx"
    output_path = os.path.join(output_dir, filename)
    
    # Check if this is test case format
    if isinstance(json_data, dict) and "test_cases" in json_data:
        file_path = generate_excel_from_testcases(
            json_data,
            output_path=output_path,
            sheet_name=sheet_name
        )
    else:
        # Generic JSON to Excel conversion.
        # Normalize into a flat list of dict records first - this correctly
        # unwraps single-key wrappers (list OR single dict), columnar data,
        # and single flat/nested records - then flattens any nested
        # dict/list field values into clean readable text per cell.
        records = _to_records(json_data)
        rows = [_flatten_row(record) for record in records]
        df = pd.DataFrame(rows)

        # Nicely capitalize headers, e.g. "test_objective" -> "Test Objective"
        # Leave already-capitalized/CamelCase headers (e.g. "TestCaseID") as-is.
        df.columns = [_prettify_header(c) for c in df.columns]

        # Write to Excel
        df.to_excel(output_path, index=False, sheet_name=sheet_name)
        
        # Apply formatting
        wb = load_workbook(output_path)
        ws = wb[sheet_name]
        
        header_fill = PatternFill(start_color="305496", end_color="305496", fill_type="solid")
        header_font = Font(color="FFFFFF", bold=True)
        wrap_alignment = Alignment(wrap_text=True, vertical="top")
        
        for col_idx, col_name in enumerate(df.columns, start=1):
            cell = ws.cell(row=1, column=col_idx)
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center", vertical="center")
            
            max_len = max(
                [len(str(col_name))]
                + [len(str(v)) for v in df[col_name].astype(str).tolist()]
            )
            col_letter = get_column_letter(col_idx)
            ws.column_dimensions[col_letter].width = min(max(max_len + 2, 12), 50)
            
            for row_idx in range(2, len(df) + 2):
                ws.cell(row=row_idx, column=col_idx).alignment = wrap_alignment
        
        ws.freeze_panes = "A2"
        wb.save(output_path)
        file_path = output_path
    
    return {
        "file_path": os.path.abspath(file_path),
        "file_name": os.path.basename(file_path)
    }
